# Custom Language File for Launcher Customizer

[ejs.app]
title = "BSLauncher"

[ejs.landing]
mediaGitHubURL = "https://github.com/dscalzi/HeliosLauncher"
mediaXURL = "#"
mediaInstagramURL = "#"
mediaYouTubeURL = "#"
mediaDiscordURL = "https://discord.gg/zNWUXdt"

[ejs.settings]
sourceGithubLink = "https://github.com/dscalZi/HeliosLauncher"
supportLink = "https://github.com/dscalZi/HeliosLauncher/issues"

[ejs.welcome]
welcomeHeader = "Bienvenue dans le launcher de BeyondSurvival!"
welcomeDescription = "Ce launcher permet d'avoir la clé pour acceder au serveur Minecraft contenant des mods et ressources."
welcomeDescCTA = "Prêt pour l'aventure ?"
